const vscode=require('vscode'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {parseRecording,Replay}=require('../player/replay');
exports.run=async()=>{
 const root=process.env.CODE_RECORDER_TEST_ROOT,folder=process.env.CODE_RECORDER_TEST_WORKSPACE;
 const uri=name=>vscode.Uri.file(path.join(folder,name));
 fs.writeFileSync(path.join(folder,'A.java'),'class A {}\r\n');
 fs.writeFileSync(path.join(folder,'B.java'),'B');
 fs.mkdirSync(path.join(folder,'node_modules'),{recursive:true});fs.writeFileSync(path.join(folder,'node_modules','ignored.js'),'secret');
 const ext=vscode.extensions.getExtension(require('../package.json').publisher+'.code-recorder-vscode');
 assert.ok(ext,'extension discovered');const {controller}=await ext.activate();
 if(process.env.CODE_RECORDER_INSTALLED_TEST==='1') assert.ok(ext.extensionPath.includes(path.join('integration','extensions')),'must exercise installed VSIX');
 const doc=await vscode.workspace.openTextDocument(uri('A.java'));const editor=await vscode.window.showTextDocument(doc);
 await editor.edit(b=>b.insert(new vscode.Position(0,0),'// initial unsaved\r\n'));
 await controller.start(vscode.Uri.file(folder));assert.ok(controller.session);
 assert.ok(controller.session.data.initial.find(f=>f.path==='A.java').text.startsWith('// initial unsaved'));
 assert.ok(!controller.session.data.initial.some(f=>f.path.includes('node_modules')));
 await editor.edit(b=>{b.insert(new vscode.Position(0,0),'// 한글😀\r\n');b.insert(new vscode.Position(2,0),'// tail\r\n');});
 await vscode.commands.executeCommand('undo');await vscode.commands.executeCommand('redo');
 let expected=doc.getText();await controller.queue;
 assert.equal(controller.session.files.get('A.java').text,expected);
 await doc.save();await controller.queue;
 const editCount=controller.session.data.events.filter(e=>e.type==='edit').length;
 await doc.save();await controller.queue;
 assert.equal(controller.session.data.events.filter(e=>e.type==='edit').length,editCount,'save alone adds no edits');
 const waitFor=async check=>{for(let i=0;i<40;i++){await new Promise(r=>setTimeout(r,100));await controller.queue;if(check())return;}assert.fail('filesystem event timeout');};
 fs.writeFileSync(path.join(folder,'External.js'),'external');
 await waitFor(()=>controller.session.files.get('External.js')?.text==='external');
 fs.writeFileSync(path.join(folder,'External.js'),'changed externally');
 await waitFor(()=>controller.session.files.get('External.js')?.text==='changed externally');
 const changes=new vscode.WorkspaceEdit();changes.renameFile(uri('B.java'),uri('Renamed.java'),{overwrite:true});
 assert.equal(await vscode.workspace.applyEdit(changes),true);await controller.queue;
 const newDoc=await vscode.workspace.openTextDocument(uri('Renamed.java'));await vscode.window.showTextDocument(newDoc);
 const deletion=new vscode.WorkspaceEdit();deletion.deleteFile(uri('Renamed.java'));await vscode.workspace.applyEdit(deletion);
 // Wait for native filesystem notifications, then compare final replay with the actual editor.
 await new Promise(resolve=>setTimeout(resolve,700));await controller.queue;
 const finalEditor=await vscode.window.showTextDocument(doc);
 await finalEditor.edit(b=>b.insert(new vscode.Position(0,0),'// final unsaved\r\n'));
 expected=doc.getText();assert.equal(doc.isDirty,true);
 const out=vscode.Uri.file(path.join(root,'integration.coderec.json'));
 const data=await controller.stop(out);assert.ok(data.events.some(e=>e.type==='edit'));assert.ok(data.events.some(e=>e.type==='move'));
 const replay=new Replay(parseRecording(fs.readFileSync(out.fsPath,'utf8')));replay.seekEvent(data.events.length);
 assert.equal([...replay.files.values()].find(f=>f.path==='A.java').text,expected);
 assert.equal([...replay.files.values()].find(f=>f.path==='External.js').text,'changed externally');
 assert.ok(![...replay.files.values()].some(f=>f.path==='Renamed.java'||f.path==='B.java'));
 const recovered=parseRecording(fs.readFileSync(controller.journal,'utf8'));assert.equal(recovered.events.length,data.events.length);
 fs.writeFileSync(path.join(root,process.env.CODE_RECORDER_INSTALLED_TEST==='1'?'installed-result.json':'result.json'),JSON.stringify({vscode:vscode.version,extensionPath:ext.extensionPath,events:data.events.length,checks:['activation','unsaved baseline','Korean and emoji','multi-edit','undo redo','save without extra events','external create and edit','rename','delete','unsaved final export','journal replay']},null,2));
};
